version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    entrypoint: bash -c 'chmod +x ../entrypoint.sh && ../entrypoint.sh'
